"""createall retirado y mejora de relationships

Revision ID: 87516adcaaf3
Revises: 853e88c81432
Create Date: 2026-02-24 16:59:07.345680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87516adcaaf3'
down_revision = '853e88c81432'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_books_user_google', ['user_id', 'google_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint('uq_books_user_google', type_='unique')

    # ### end Alembic commands ###
